package com.nautilus.omni.model.dto;

public enum OmniMachineType {
    MY14_TREADMILL("MY14_TREADMILL"),
    MY14_BIKE_ELLIPTICAL("MY14_BIKE_ELLIPTICAL"),
    MY16_TREADMILL("MY16_TREADMILL"),
    MY16_BIKE_ELLIPTICAL("MY16_BIKE_ELLIPTICAL"),
    MY16_INTERNATIONAL_TREADMILL("MY16_INTERNATIONAL_TREADMILL"),
    ELLIPTICAL_E628_INTERNATIONAL("ELLIPTICAL_E628_INTERNATIONAL"),
    UPRIGHT_BIKE_UR628_INTERNATIONAL("UPRIGHT_BIKE_UR628_INTERNATIONAL"),
    MY16_INTERNATIONAL_RECUMBENT_BIKE("MY16_INTERNATIONAL_RECUMBENT_BIKE"),
    MY17_TREADMILL_T618("MY17_TREADMILL_T618"),
    MY17_ELLIPTICAL_E618("MY17_ELLIPTICAL_E618"),
    MY17_BIKE_B618("MY17_BIKE_B618"),
    MY17_TREADMILL_T616("MY17_TREADMILL_T616"),
    MY17_ELLIPTICAL_E616("MY17_ELLIPTICAL_E616"),
    MY17_UPRIGHT_BIKE_UR616("MY17_UPRIGHT_BIKE_UR616");
    
    String mType;

    private OmniMachineType(String type) {
        this.mType = type;
    }

    public String getType() {
        return this.mType;
    }
}
